### ISSUE TITLE
Order Status wird nicht aktualisiert

### ISSUE THREAD

**Issue by DavidZebris** [gonzaraweb/OrderingMediators#13]
Ich habe 2 Orders (Nr. 912 und 913) aufgegeben, die an und für sich korrekt bearbeitet wurden: Die Downloads wurden korrekt durchgeführt und das Consolidation-Module ist durchgelaufen und hat "Done" als Status für seinen Job abgespeichert.

Aber wenn ich den Status der Order abfrage bekomme ich (auch nach längerem Warten) nur ein "partial".

Die Fehlermeldungen in der Konsole sehen für mich so aus, als würde das IDP den GetJobStatus-Service vom Consolidation Module nicht erreichen.

**Comment by DavidZebris** [comment]
Das ist auf dem IDP-Dev immer noch so, Beispiele sind die Orders 1869, 1870, 1871, 1872 und 1873: das Consolidation-Module ist durchgelaufen und hat DONE als Ergebnis gespeichert, die Dateien sehen auch OK aus, aber wenn man den Order-Status abfragt, bekommt man immer nur ein "partial".

**Comment by FabianVista** [comment]
Ich habe auch eine Order(1307) die seit ca 18 Stunden auf partial steht.

**Comment by FabianVista** [comment]
Die Orders die ich im IDP(nicht _DEV) absetze bleiben immer noch auf partial(z.B. 1311). Es wäre gut wenn das demnächst behoben wird, da ich ansonsten nichts testen und nicht weiterarbeiten kann.

**Comment by DavidZebris** [comment]
Aktueller Status im IDP-Dev:
Es kommt eine Fehler-Meldung "No Order was found for OrderId (..)".
