### ISSUE TITLE
RE Orders unvollständig (=Download-Fehler bei großen Bestellungen)

### ISSUE THREAD

**Issue by FabianVista** [gonzaraweb/OrderingMediators#2]
Die RapidEye Orders sind immer noch unvollständig, bei meinen letzten Orders waren auch kleine Bestellungen von z.B. einer Szene nicht vollständig(z.B. Order 726).

**Comment by DavidZebris** [comment]
Das kann auch ein Folgefehler sein: 
Wenn die Szene, die du jetzt einzeln bestellt hast, vorher schonmal in einer größeren Order dabei war, und dabei nicht richtig geladen wurde, bekommst du jetzt wieder nur die halbe Datei, weil er sie nicht nochmal neu runterlädt.
(Dass 'größere' Orders mit mehreren RapidEye-Daten zu fehlerhaften Dateien führen, kennen wir ja schon..)

PS:
In einer Testorder mit 5 RE-Szenen ließ sich bei mir eben auch keine einzige Datei öffnen, die waren alle zu klein, also fehlerhafte Downloads.

**Comment by DavidZebris** [comment]
Update: Fehler tritt noch auf, allerdings meldet der GetStatusService jetzt korrekt, dass die Order failed ist. Man sollte also keine Erfolgsmeldung mehr bekommen und dann erst nach dem Download feststellen, dass der Inhalt der ZIP-Datei fehlerhaft ist.

**Comment by DavidZebris** [comment]
Ich habe 4 größere Orders zum Testen angelegt:
Nr. 838 und 839 mit je 5 RapidEye-Dateien
Nr. 840 mit 10 RapidEye-Dateien
Nr. 841 mit 15 RapidEye-Dateien

**Comment by gonzaraweb** [comment]
Download are big therefore we have to extends the thread timeout. Now it is 20 minutes. Meanwhile the DB connection is also get invalid and cant not update the status.

**Comment by DavidZebris** [comment]
Ich habe eine Bestellung mit 2 RapidEye-Datensätzen aufgegeben (Order Nr. 842), bei der sich auch nach längerer Wartezeit nichts zu tun scheint. 
Von der Geschwindigkeit der Downloads in der Cloud her müsste das eigentlich längst erledigt sein..

EDIT:
Das lag daran, dass die Wiederholungen für den Downloader im WSO2 auf 1 statt auf -1 (unendlich) standen.
Wenn der Downloader richtig funktioniert, kommt wieder die bekannte Fehlermeldung: Konnte auch nach 3 Versuchen nicht geladen werden..

**Comment by DavidZebris** [comment]
Kommentar war beim falschem Issue.

**Comment by DavidZebris** [comment]
Bei einer Bestellung mit 20 MCD12-Dateien a 80 MB gab es keine Download-Probleme.
Eine Bestellung mit 2 oder 4 RE-Dateien hat heute auch zum ersten Mal richtig funktioniert.

Wurde hier etwas verändert ?
