### ISSUE TITLE
Fehlender Slot ascendingNodeDate beim Einfügen von Metadaten

### ISSUE THREAD

**Issue by DavidZebris** [gonzaraweb/OrderingMediators#23]
Beim Einfügen von Metadaten in den Katalog habe ich folgenden Fehler bekommen:

WARNUNG: Error while committing data
java.sql.SQLException: Could not create slots
Slot urn:ogc:def:ebRIM-Slot:OGC-06-131:ascendingNodeDate of object urn:MYD14:2122002412 is not registered yet.

Das ist wahrscheinlich beim Löschen des Katalog-Inhaltes passiert ?
Am Metadaten-Einlesen haben wir schon länger nichts mehr verändert.

**Comment by gonzaraweb** [comment]
In dev habe ich den Slot eingefügt

**Comment by DavidZebris** [comment]
Ich bekomme leider (DataInputPortalDev) immer noch eine ähnliche Fehlermeldung:

WARNUNG: Failed to insert objects
java.sql.SQLException: Could not create slots
Slot urn:ogc:def:ebRIM-Slot:OGC-06-131:ascendingNodeDate of object urn:MYD14:2122002412 is not registered yet

**Comment by gonzaraweb** [comment]
sorry leider ist die slot definition gecached ohne neue Start des AS funktioniert es nicht. Ich habe den Server wieder startet. Probiert noch mal

**Comment by DavidZebris** [comment]
OK, funktioniert jetzt.
