### ISSUE TITLE
Ordering Problem

### ISSUE THREAD

**Issue by FabianVista** [gonzaraweb/OrderingMediators#24]
Order Endpoint returns http response code 500 for Order XML that worked with older IDP versions.

**Comment by gonzaraweb** [comment]
Hallo Fabian,

Das Produkt beispielweiß3 3361205_2013-04-15_RE5_3A_169320 existiert nicht sonder im Form von urn:3261224:2013-04-15:RE5:3A:169321 oder urn:3361205:2013-04-15:RE5:3A:169320.  Keine Ahnung woher bekommt der PHP Client diese Produkten aber nicht vom Dev Katalog.

**Comment by FabianVista** [comment]
Ich arbeite nicht mit dem php client, dieser wäre nur nützlich um meinen code zu überprüfen. Ich verstehe Deine Antwort nicht ganz, ich habe jetzt versucht in der Soap -Nachricht die Identifier nicht in der Form 3361205_2013-04-15_RE5_3A_169320, sondern mit derm voangestellten urn:, also urn:3361205:2013-04-15:RE5:3A:169320 zu übergeben, das hat aber die selbe Fehlermeldung zur Folge.

**Comment by gonzaraweb** [comment]
Der PHP Client wurde von David Leimbach aus Zebris geschrieben und er ist in Urlaub. Gestern Nacht habe ich eine neue Version der Ordering plus die Internet Endpoints freigegen. Bitte probiert jetzt sie und wenn du Fehler bekommst einfach das Screenshot hier mitkopieren

**Comment by FabianVista** [comment]
Mit den neuen Endpoints bekomme ich ein connection time out(Schon bei der Suche im Katalog). Vorher waren die Endpoints ja interne IPs, ist es gewollt das jetzt innerhalb der Cloud über externe IPs auf den Katalog zugegriffen wird?
![unbenannt](https://cloud.githubusercontent.com/assets/8362940/8517127/6caa5062-23bd-11e5-9013-142f64b11f33.JPG)

**Comment by FabianVista** [comment]
Im Post musste das Request Property "SOAPAction" auf "Submit" gesetzt werden, danach hat die Abgabe der Order funktioniert.
