### ISSUE TITLE
Probleme beim Anlegen und Abfragen eines Consolidation Jobs

### ISSUE THREAD

**Issue by DavidZebris** [gonzaraweb/OrderingMediators#29]
Der Service zum Anlegen der Consolidation Jobs scheint nicht mehr richtig aufgerufen zu werden:
Nach dem Download wird in der Konsole angezeigt, dass der Service aufgerufen wird, aber der Code des Services selber wird anscheinend trotzdem nicht ausgeführt.

Er sollte Ausgaben in der Konsole machen und Text in ein Logfile schreiben, was aber beides nicht passiert, die erste Zeile des im Service ausgeführten Codes lautet z.B.:
Out.WriteLn("\r\nStart Insert Consolidation-Job Service:");
Das sollte in der Konsole des WSO2-MB erscheinen.

In der Benutzeroberfläche vom WSO2 Message Broker steht:
Request Count: 6
Response Count: 0
Fault Count: 6

Das heisst natürlich auch, dass im Moment alle Orders mit FAILED enden.

**Comment by DavidZebris** [comment]
Etwas Ähnliches scheint auch beim GetStatus-Service zu passieren:
Es kommen immer wieder Meldungen "Starting Consolidation Status Check / No Consolidation Job found! / Consolidation Status Check end", aber der Service wird gar nicht aufgerufen (hier ist der Request Count = 0).

**Comment by gonzaraweb** [comment]
Ok. Ich probiere mit soapui

**Comment by gonzaraweb** [comment]
Bei der Importieung der consolstatus wsdl vom https://217.150.144.19/services/getstatus_service?wsdl2 
bekomme ich:  WSDLException (at /wsdl2:description): faultCode=INVALID_WSDL: Expected element '{http://schemas.xmlsoap.org/wsdl/}definitions'.

**Comment by DavidZebris** [comment]
Die einzige Änderung beim WSDL in den letzten Monaten war dass ich ein Feld bei der Request entfernt habe:
xs:element name="productType" nillable="false" type="xs:string"/
(Zeile entfernt)

**Comment by DavidZebris** [comment]
Ich konnte aus dem WSDL für den CreateconsolidationJob_Service problemlos ein SOAPUI-Projekt erstellen. Dort musste ich nur noch den korrekten Endpoint einsetzen und die Felder füllen, danach konnte ich den Request erfolgreich abschicken.

In der Konsole vom WSO2-MB sind daraufhin mehrere Zeilen Text erschienen, angefangen mit "Start Insert Consolidation -Job Service:" und der Job wurde erfolgreich in der Tabelle angelegt.
(Beim Versuch ihn auszuführen wird er später natürlich auf FAILED gehen weil ich in die Felder nur sinnloses Zeug geschrieben habe)

Beim Versuch die Consolidation-Jobs für die echten Orders anzulegen kommt weder die Textausgabe in der WSO2-MB-Konsole noch wird der Job in die Tabelle geschrieben.

**Comment by DavidZebris** [comment]
Beim GetStatus-Service hat das in SOAPUI auch problemlos geklappt: WSDL einlesen, Endpoint anpassen, Nummer eines Jobs angeben (siehe Tabelle), Request abschicken, Resposne erhalten.

Benutzt habe ich die WSDLs, die ich hier lokal auf dem Rechner liegen habe, und die ich auch benutze um den Code für die Services automatisch zu generieren.
Die Dateien liegen im Download-Ordner von Root.

Sind die vielleicht unterschiedlich zu dem WSDL, das du benutzt hast ?

PS:
Habe dir meine Version der WSDLs auch nochmal per Mail geschickt.

**Comment by DavidZebris** [comment]
Zur Kontrolle, der InsertConsolidationJob_Service sollte in etwa solche Ausgaben in der WSO2-Konsole erzeugen:
Start Insert Consolidation-Job Service:
Folder: test
ParentID: RapidEye
Command: ConsolidationModule
Status: NEW
Ordering Options: 
hallo
Searching for existing jobs (NEW or WORK) with the same parameters..
Insert Consolidation-Job-Service done.

Und der GetStatus-Service eine solche Zeile:
GetStatus-Service done (Job 990 = DONE).

**Comment by DavidZebris** [comment]
@Abel:
Hast du vielleicht etwas am Aufruf des InsertConsolidationJob-Services geändert ?
(z.B. schon die WSAdressing-Infos hinzugefügt, die im WSDL des Services nicht vorgesehen sind)

Der Service reagiert im Moment so wie wenn man in SOAPUI ein fehlerhaftes XML schickt, dann wird der Java-Code im Service selber auch erst gar nicht aufgerufen.

Du müsstest mal schauen welche Fehlermeldung du bekommst wenn du versuchst den Consolidation-Job anzulegen, denn was mich angeht funktioniert der Service eigentlich so wie er sollte (siehe SOAPUI).

**Comment by DavidZebris** [comment]
Lag wohl nur an fehlenden Klammern < > im Request-XML, scheint jetzt wieder zu gehen.
