### ISSUE TITLE
Bestellung mit Platzhalter in der URL

### ISSUE THREAD

**Issue by DavidZebris** [gonzaraweb/OrderingMediators#3]
Wenn ich einen MODIS-active fires - Datensatz mit \* in der URL bestelle, bekomme ich eine Fehlermeldung, der Download funktioniert nicht.

**Comment by gonzaraweb** [comment]
Bitte schreibt hier die Adresse

**Comment by DavidZebris** [comment]
zB Order Nummer 725.

**Comment by gonzaraweb** [comment]
Nach lange Zeit ist jetzt erledigt. Sicherung bei download, wenn unterbrochen. Full FTP Support

**Comment by DavidZebris** [comment]
OK, funktioniert jetzt.
